### ISSUE TITLE
The click animation was removed in the last release

### ISSUE THREAD

**Issue by Enevevet** [peaillaud/The_social_button#1]
https://stackoverflow.com/a/55954610/14122161

**Comment by Enevevet** [comment]
???

**Comment by peaillaud** [comment]
The click animation wasn't removed since I only changed the color of the button. If you don't see it, try to disable dark mode.

**Comment by Enevevet** [comment]
![IMG_20210811_234306.jpg](https://user-images.githubusercontent.com/39494222/129107366-daf437d8-fa9a-4f72-a726-2f2f8b449ddb.jpg)

**Comment by peaillaud** [comment]
Should be resovled in last release.
